name: Build and Test the skeleton app

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Setup Java JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check project build
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_EDGE_PASSWORD: ${{ secrets.ARTIFACTORY_EDGE_PASSWORD }}
        run: ./gradlew clean loader:build
